Feature/switch switch group components
midasit-dev/moaui pull request #24
Opened 2023-08-11 04:32 UTC by kh1012

체크박스를 참고해서 맛나게 개발했습니다 :)

2023-08-11 04:32 UTC, kh1012 commented
main을 당겨왔더니 다른 커밋들이 포함되어 버렸네요

2023-08-11 04:49 UTC, bce0404 commented on src/lib/SwitchGroup/Demo.tsx
> +				<Switch label="test1" checked={values?.test1} onChange={handleCheckboxChange} />
onChange Event handler가 "name" 으로 들어온 값을 받아 상태를 제어하기 때문에, <Switch name={"test1"}와 같이 식별 가능한 값을 추가해주어야 합니다.

2023-08-11 04:55 UTC, bce0404 requested changes
확인 부탁드립니다.

2023-08-11 04:55 UTC, bce0404 commented on src/lib/Switch/Styled.tsx
> +				padding: 0,
특이하게 기획안에 disabled 상태의 label 색상값과 enabled 상태의 label 색상값이 변경 없이 text/secondary를 사용하게 되어 있습니다.
지금은 disabled 되었을 때 label에 mui 기본 투명도(0.38)가 적용되는 상태이니 확인 부탁드립니다.

2023-08-11 04:55 UTC, bce0404 commented on src/lib/Switch/Styled.tsx
> +							transition: 'background-color 500ms linear',
MuiSwitch-switchBase에는 transitionDuration이 적용되어 있지만, track에는 없어서 테두리와 배경 색 애니메이션이 따로 동작하고 있는 것 같습니다.

2023-08-11 04:59 UTC, bce0404 commented
> main을 당겨왔더니 다른 커밋들이 포함되어 버렸네요

체크박스 변경사항이 아직 dev에 반영되지 않은 관계로 반영 후 dev로 한 번 끌어왔습니다.
이전에 변경한 부분 중 동작에 영향을 주는 부분이 있는 관계로 위 change request 메시지 참고하셔서 변경 부탁드립니다 :)

2023-08-13 08:57 UTC, HY0118 commented on src/lib/Switch/Styled.tsx
> +							'&.Mui-disabled + .MuiSwitch-track': {
오.. + 를 쓸 수 있군요?!

2023-08-16 02:39 UTC, HY0118 approved these changes
Approve!
댓글 확인 부탁드립니당~

2023-08-16 02:39 UTC, HY0118 commented on src/lib/Switch/Styled.tsx
> +							borderRadius: 26 / 2,
혹시 Radius 값을 이렇게 지정한 이유가 있을까요~?

2023-08-16 02:39 UTC, HY0118 commented on src/lib/SwitchGroup/index.tsx
> +export default function MoaSwitchGroup(props: StyledProps): JSX.Element {
JSX.Element 는 다른 PR에서 언급드렸기 때문에 만약 변경된다면 일괄 변경 부탁드립니다 :)

2023-08-16 04:37 UTC, merged