Feature/tab tab group tab panel group component
midasit-dev/moaui pull request #27
Opened 2023-08-14 02:03 UTC by kh1012

Tab/TabGroup 개발 완료
TabPanelGroup은.. 조금 더 고민이 필요한데, 플러그인 적용하면서 추가 개발을 부탁 드립니다ㅠ

2023-08-14 08:33 UTC, bce0404 commented
PR 목적지가 dev가 아닌 main으로 되어있습니다.

2023-08-16 02:20 UTC, kh1012 commented
앗 변경되었네요.
dev로 되어 있는데 approve 해주시는건가요

2023-08-16 02:28 UTC, HY0118 requested changes
Code Review

2023-08-16 02:28 UTC, HY0118 commented on src/lib/Tab/Styled.tsx
> +	 * @default false
defaultValue로 수정 부탁드립니당

2023-08-16 02:28 UTC, HY0118 commented on src/lib/Tab/index.tsx
> +export default function MoaTab(props: StyledProps) : JSX.Element { return ( <StyledComponent {...props} /> ) }
함수형 컴포넌트의 반환형은 JSX.Element보다는 React.Element를 쓰는 것이 일반적인 것 같습니다.
![image](https://github.com/midasit-dev/moaui/assets/40168374/1b555827-adb3-4692-bf73-deacb97ed014)
![image](https://github.com/midasit-dev/moaui/assets/40168374/4ad5eca2-ab8b-43b2-9b99-947aec9f85c7)

2023-08-16 02:28 UTC, HY0118 commented on src/lib/TabGroup/Styled.tsx
> +	if (!props?.children) return (<></>);
음 이런 조건문이 필요한거라면 children type이 optional 하지 않게 변경하고, defaultProps를 넣어주는 방법은 어떨까요?

2023-08-16 03:49 UTC, kh1012 commented on src/lib/TabGroup/Styled.tsx
> +	if (!props?.children) return (<></>);
크 멋진 리뷰입니다

2023-08-16 03:49 UTC, kh1012 commented on src/lib/Tab/Styled.tsx
> +	 * @default false
넵 알겠습니다ㅋ

2023-08-16 05:05 UTC, bce0404 approved these changes
Approve!

2023-08-16 05:05 UTC, HY0118 commented on src/lib/TabGroup/index.tsx
> +export default function MoaTabGroup(props: StyledProps) : JSX.Element { return ( <StyledComponent {...props} /> ) }
앗 ㅋㅋ 이 부분은 변경되지 않은 것 같습니다.

2023-08-16 05:06 UTC, bce0404 commented
> 앗 변경되었네요. dev로 되어 있는데 approve 해주시는건가요

제가 못 바꾸는 분류인줄 알았으나 바꿀 수 있었습니다.
approve했습니다 :)

2023-08-17 07:29 UTC, HY0118 commented on src/lib/TabGroup/index.tsx
> +export default function MoaTabGroup(props: StyledProps) : JSX.Element { return ( <StyledComponent {...props} /> ) }
바쁘신것 같아 제가 수정했습니당

2023-08-17 07:30 UTC, HY0118 approved these changes

2023-08-17 08:13 UTC, merged