Feature/seperator
midasit-dev/moaui pull request #31
Opened 2023-08-14 08:57 UTC by HY0118

Seperator 디자인 반영안 개발
props는 Direction으로 "horizontal" | "vertical" 만 받도록 개발

![image](https://github.com/midasit-dev/moaui/assets/40168374/b41cbd69-8054-4699-85ac-6de1bad1538c)

2023-08-14 09:01 UTC, bce0404 requested changes
properties 네이밍 규칙 관련으로 확인 부탁드립니다.

2023-08-14 09:01 UTC, bce0404 commented on src/lib/Seperator/index.tsx
> +	Direction: "horizontal"
다른 properties가 소문자로 시작하기 때문에 여기도 소문자 direction으로 바꾸어 주세요!

2023-08-14 09:07 UTC, HY0118 commented on src/lib/Seperator/index.tsx
> +	Direction: "horizontal"
넵 수정해서 반영했습니당~! ㅎㅎ

2023-08-14 09:08 UTC, bce0404 approved these changes
approve!

2023-08-16 02:19 UTC, kh1012 approved these changes
apprival!

2023-08-17 07:23 UTC, merged