Issue_#34 - TextField에 onChange 이벤트 추가
midasit-dev/moaui pull request #36
Opened 2023-08-18 05:59 UTC by HY0118

2023-08-18 06:58 UTC, bce0404 requested changes
코드에서는 문제가 없어 보였는데, 직접 컴포넌트를 동작시켜보니 onChange 이벤트가 실행되지 않았습니다.
확인 부탁드립니다.

2023-08-18 07:02 UTC, bce0404 commented
@HY0118 
확인해보니 defaultValue 값이 있는 경우 uncontrolled 상태로 취급되어 onChange 이벤트가 발생되지 않았습니다.
defaultValue를 defaultProps에서 제거하면 onChange 이벤트가 발생되네요.

defaultProps에서 defaultValue 제거하는 방향으로 고려해주세요!

2023-08-18 07:51 UTC, HY0118 commented
> 코드에서는 문제가 없어 보였는데, 직접 컴포넌트를 동작시켜보니 onChange 이벤트가 실행되지 않았습니다. 확인 부탁드립니다.

![image](https://github.com/midasit-dev/moaui/assets/40168374/a8daf375-63ad-4fac-8d2d-d83b35c1d862)

![image](https://github.com/midasit-dev/moaui/assets/40168374/585be31b-e4a0-4611-983d-09ff4c6a9295)

아 혹시 저것도 익명함수를 바로 써서 나타난 문제인지 확인 부탁드립니다.

제가 짠 demo 코드에서는 defaultValue썼고 익명함수는 아닌데 정상 동작해서요~!

2023-08-21 00:20 UTC, bce0404 commented
> > 코드에서는 문제가 없어 보였는데, 직접 컴포넌트를 동작시켜보니 onChange 이벤트가 실행되지 않았습니다. 확인 부탁드립니다.
> 
> ![image](https://user-images.githubusercontent.com/40168374/261538006-cc0a6d09-b17a-47bb-ad4b-489f1b6f1eca.png)
> 
> ![image](https://user-images.githubusercontent.com/40168374/261537074-585be31b-e4a0-4611-983d-09ff4c6a9295.png)
> 
> 아 혹시 저것도 익명함수를 바로 써서 나타난 문제인지 확인 부탁드립니다.
> 
> 제가 짠 demo 코드에서는 defaultValue썼고 익명함수는 아닌데 정상 동작해서요~!

확인해보니 익명/일반 함수 둘 다에서 정상 작동합니다.
#35 코드를 써서 onChange 이벤트가 안 들어갔나봐요..

정상 작동합니다 :) 감사합니다!

2023-08-21 00:20 UTC, bce0404 approved these changes
Approve!

2023-08-21 01:10 UTC, merged